// RIDING-COMPLEX-PUBLICATION - pure flatten of the live block -> station ->
// pair tree into three flat, ordered arrays for BATCHED publication-snapshot
// creation (one call per level), replacing the previous per-row create loop
// in publishComplexRidingPlanInternal (lib/actions/riding-slot-complex-publications.ts).
// No Prisma import, no id generation, no clock, no randomness - every
// publication row's own id is generated by the DB layer (createManyAndReturn),
// never invented here. Every flat row keeps its live (source) id so the write
// layer can wire each batch's DB-generated id back to the right parent after
// each insert, without depending on insertion/return order.

export interface LivePairForPublication {
  id: string;
  trainee1Id: string | null;
  trainee2Id: string | null;
  horseName: string | null;
  sortOrder: number;
  trainee1: { fullName: string } | null;
  trainee2: { fullName: string } | null;
}

export interface LiveStationForPublication {
  id: string;
  instructorId: string | null;
  arena: string | null;
  sortOrder: number;
  instructor: { fullName: string } | null;
  pairs: readonly LivePairForPublication[];
}

export interface LiveBlockForPublication {
  id: string;
  startTime: string;
  endTime: string;
  sortOrder: number;
  stations: readonly LiveStationForPublication[];
}

export interface FlatPublicationBlockInput {
  sourceBlockId: string;
  startTime: string;
  endTime: string;
  sortOrder: number;
}

export interface FlatPublicationStationInput {
  sourceBlockId: string;
  sourceStationId: string;
  instructorId: string | null;
  instructorNameSnapshot: string | null;
  arena: string | null;
  sortOrder: number;
}

export interface FlatPublicationPairInput {
  sourceStationId: string;
  sourcePairId: string;
  trainee1Id: string | null;
  trainee1NameSnapshot: string | null;
  trainee2Id: string | null;
  trainee2NameSnapshot: string | null;
  horseName: string | null;
  sortOrder: number;
}

export interface FlattenedComplexPlanPublicationTree {
  blocks: FlatPublicationBlockInput[];
  stations: FlatPublicationStationInput[];
  pairs: FlatPublicationPairInput[];
}

/**
 * Flatten preserves the exact same field mapping the previous per-row create
 * loop used (sourceBlockId: block.id, instructorNameSnapshot: instructor?.fullName
 * ?? null, etc.) and the exact same traversal order (blocks by their given
 * order, then each block's stations, then each station's pairs) - the output
 * arrays are in stable depth-first order, matching what the old sequential
 * loop wrote row-by-row.
 */
export function flattenComplexPlanForPublication(
  blocks: readonly LiveBlockForPublication[]
): FlattenedComplexPlanPublicationTree {
  const flatBlocks: FlatPublicationBlockInput[] = [];
  const flatStations: FlatPublicationStationInput[] = [];
  const flatPairs: FlatPublicationPairInput[] = [];

  for (const block of blocks) {
    flatBlocks.push({
      sourceBlockId: block.id,
      startTime: block.startTime,
      endTime: block.endTime,
      sortOrder: block.sortOrder,
    });

    for (const station of block.stations) {
      flatStations.push({
        sourceBlockId: block.id,
        sourceStationId: station.id,
        instructorId: station.instructorId,
        instructorNameSnapshot: station.instructor?.fullName ?? null,
        arena: station.arena,
        sortOrder: station.sortOrder,
      });

      for (const pair of station.pairs) {
        flatPairs.push({
          sourceStationId: station.id,
          sourcePairId: pair.id,
          trainee1Id: pair.trainee1Id,
          trainee1NameSnapshot: pair.trainee1?.fullName ?? null,
          trainee2Id: pair.trainee2Id,
          trainee2NameSnapshot: pair.trainee2?.fullName ?? null,
          horseName: pair.horseName,
          sortOrder: pair.sortOrder,
        });
      }
    }
  }

  return { blocks: flatBlocks, stations: flatStations, pairs: flatPairs };
}
